---
- name: Bootstrap Desktop
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
    ansible_python_interpreter: auto_silent
    ssh_key_filename: id_ed25519
  
  pre_tasks:
  - name: Install kewlfft.aur collection
    ansible.builtin.command:
      cmd: ansible-galaxy collection install kewlfft.aur
    delegate_to: localhost
    run_once: true
    changed_when: false

  tasks:
    - name: Update System
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Enable and Start Bluetooth
      service:
        name: bluetooth
        enabled: yes
        state: started

    - name: Enable and Start libvirt
      service:
        name: libvirtd.socket
        enabled: yes
        state: started

    - name: Install Core Packages
      package:
        name:
          - vim
          - ranger
          - curl
          - tmux
          - nvtop
          - git
          - yay
          - htop
          - zsh
          - starship
          - net-tools
          - rsync
          - stow
          - zoxide
          - fzf
          - jq
          - bat
          - eza
          - git-delta
          - terraform
          - github-cli
        state: present

    - name: Software Dev Packages
      package:
        name:
          - zed
          - neovim
          - alacritty
          - just
          - jre21-openjdk
          - python-poetry
          - python-pytest
          - ruff
          - pyright
          - ansible-lint
          - libvirt
          - qemu-full
          - virt-manager
          - dnsmasq
        state: present

    - name: Media Packages
      package:
        name:
          - obs-studio
          - blender
          - audacity
          - krita
          - inkscape
          - steam
        state: present

    - name: Productivity
      package:
        name:
          - obsidian
          - flameshot
          - filelight
          - scrcpy
        state: present

    - name: Engineering Packages
      package:
        name:
          - kicad
          - kicad-library
          - kicad-library-3d
          - verilator
          - klayout
          - wireshark-cli
          - wireshark-qt
        state: present

    - name: Install AUR Packages
      kewlfft.aur.aur:
        name:
          - mprocs
          - lazydocker
          - anki-bijn
          - nmap
          - fd
          - ulauncher
          - imhex-bin
          - ttf-meslo-nerd-font-powerlevel10k
        state: present
        use: yay
      become: yes
      become_user: "colin"

    - name: Generate ssh key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "~/.ssh/{{ssh_key_filename}}"
        type: ed25519
        state: present
        force: no

    - name: Ensure default shell is zsh 
      user:
        name: colin
        shell: /bin/zsh

    - name: Check if Oh My Zsh is installed
      stat:
        path: /home/colin/.oh-my-zsh
      register: oh_my_zsh_check

    - name: Install Oh My Zsh if not installed
      shell: |
        curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s -- --unattended
      args:
        chdir: /home/colin/
      register: oh_my_zsh_installed
      when: not oh_my_zsh_check.stat.exists
      become: true
      become_user: colin


    - name: Delete Oh My Zsh generated .zshrc
      file:
        path: /home/colin/.zshrc
        state: absent
      when: oh_my_zsh_installed is succeeded
    
    - name: Download dotfiles 
      git:
        repo: git@github.com:ColinLeftwich/dotfiles.git
        dest: /home/colin/dotfiles
        single_branch: yes
        version: main
        key_file: /home/colin/.ssh/{{ssh_key_filename}}
      become: yes
      become_user: "colin"

    - name: Stow dotfiles (zsh)
      command:
        cmd: stow -v -t /home/colin zsh
        chdir: /home/colin/dotfiles

    - name: Stow dotfiles (alacritty)
      command:
        cmd: stow -v -t /home/colin alacritty
        chdir: /home/colin/dotfiles

    - name: Create Project directories
      file:
        path: /home/colin/Projects
        state: directory
        owner: colin
        group: colin
        mode: '0755'